<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>41a83e57-abec-40ea-aa0a-6d9d9efca260</elementGuidId>
    <imagePath></imagePath>
    <name>input_radio_buttons_group_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[3]/div[2]/label[3]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[rnd-id='\35 1']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'radio-buttons-group') and equals(@class,'PrivateSwitchBase-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input css-1m9pwf3</value>
        <webElementGuid>8a3fb334-94f8-4280-a278-093a10953d5b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>radio-buttons-group</value>
        <webElementGuid>d5b1ee6d-6c25-4879-b46c-06c7bcfcdaf3</webElementGuid>
    </webElementProperties>
</WebElementEntity>