<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0100dbe0-6c7f-4882-8848-45694e61583d</elementGuidId>
    <imagePath></imagePath>
    <name>input_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[2]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[rnd-id='\37 ']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'PrivateSwitchBase-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input css-1m9pwf3</value>
        <webElementGuid>8c2014ba-7fac-42f4-8d4a-73268184ad49</webElementGuid>
    </webElementProperties>
</WebElementEntity>