<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>63a3e276-9017-4f4f-8ed0-30346e84082b</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[2]/label[2]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[rnd-id='\31 4']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'PrivateSwitchBase-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input css-1m9pwf3</value>
        <webElementGuid>1a2d7459-d14f-4bfe-ab69-28c1c9a10bb9</webElementGuid>
    </webElementProperties>
</WebElementEntity>