<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>06691aea-beac-49f8-bd4d-9858d0af4ad7</elementGuidId>
    <imagePath></imagePath>
    <name>input_radio_buttons_group_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[3]/div[2]/label[2]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[rnd-id='\34 1']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'radio-buttons-group') and equals(@class,'PrivateSwitchBase-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input css-1m9pwf3</value>
        <webElementGuid>c43d9db9-539a-4918-8883-d509dd9bbda1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>radio-buttons-group</value>
        <webElementGuid>698a1f5e-3b2f-4ae9-ae8d-8e60c2f31072</webElementGuid>
    </webElementProperties>
</WebElementEntity>