<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0612a032-ffa1-4c79-87fc-0c09664608c2</elementGuidId>
    <imagePath></imagePath>
    <name>input_radio_buttons_group</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[3]/div[2]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[rnd-id='\33 1']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'radio-buttons-group') and equals(@class,'PrivateSwitchBase-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input css-1m9pwf3</value>
        <webElementGuid>41942f10-6fe9-43c4-af48-799d78e9f5b9</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>radio-buttons-group</value>
        <webElementGuid>abd88258-c03c-4f15-bb66-c30cd122a391</webElementGuid>
    </webElementProperties>
</WebElementEntity>