<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>44deb624-439a-4896-98bf-13905248e6c7</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>('//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[2]/label[1]/span[1]/input[1]',)</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>